name: Fluxo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Build
      working-directory: ./app
      run: go build -v main.go
      
    - name: Test
      working-directory: ./app    
      run: go test -v main.go

  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Test
      working-directory: ./app
      run: go test -v main.go
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    environment: gcp-prod
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/site:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{secrets.GCP_PROJECT_ID }}
          
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
        
      - name: Build Docker Image
        working-directory: ./app      
        run: docker build -t $IMAGE_NAME .
        
      - name: Push Docker Image
        working-directory: ./app        
        run: docker push $IMAGE_NAME
      
      - name: Deploy Docker Image
        working-directory: ./app      
        run: gcloud run deploy site --image $IMAGE_NAME --region us-central1 --memory 128Mi --min-instances 0 --max-instances 1 --platform managed --port 8006 --allow-unauthenticated
